{
    "name": "EnzNode API",
    "description": """The Rest API for Odoo 16""",
    "summary": """This app helps to interact with odoo
     backend with help of rest api requests""",
    "category": "Tools",
    "version": "16.0.1.0.0",
    'author': 'Enzapps',
    'company': 'Enzapps',
    'maintainer': 'Enzapps',
    'website': "https://www.enzapps.com",
    "depends": ['base', 'web','mail','hr','contacts'],
    "data": [
        'security/ir.model.access.csv',
        'data/service.xml',
        'views/res_number_plate.xml',
        'views/res_camera.xml',
        'views/vehicle_log.xml',
        'views/attendance_log.xml',
        'views/res_users.xml',
        'views/res_detection_services.xml',
        'views/res_parking_rate.xml',
    ],
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
